spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE}
  cloud:
    openfeign:
      querymap:
        enabled: true

info:
  app:
    name: QBIT-API
    version: 5.1.1 # TODO: develop->deploy PR 시 수정
    description: QBIT 백엔드 API