server:
  port: ${REALTIME_SERVER_PORT_DEV}

spring:
  data:
    redis:
      host: ${REDIS_HOST_DEV}
      port: ${REDIS_PORT_DEV}
      password: ${REDIS_PASSWORD_DEV}
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0

# WebSocket
websocket:
  message-size-limit: 8192
  buffer-size-limit: 8192

# JWT
jwt:
  secret:
    access: ${JWT_ACCESS_SECRET_DEV}
    refresh: ${JWT_REFRESH_SECRET_DEV}

logging:
  level:
    root: INFO
    com.curihous.qbit: DEBUG
    org.springframework.web.socket: DEBUG

